services:
    simple_api_client.transport.guzzle:
        class: SimpleApiClientBundle\Service\Transport\GuzzleAdaptor

    simple_api_client.client:
        class: SimpleApiClientBundle\Service\ApiClient
        arguments:
          - '@simple_api_client.transport.guzzle'
        public: true